Remove html-proofer
It failed to install on travis
```
$ gem install html-proofer
Fetching: concurrent-ruby-1.0.5.gem (100%)
Successfully installed concurrent-ruby-1.0.5
Fetching: minitest-5.10.1.gem (100%)
Successfully installed minitest-5.10.1
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.8.1.gem (100%)
Successfully installed i18n-0.8.1
Fetching: activesupport-5.0.2.gem (100%)
ERROR:  Error installing html-proofer:
    activesupport requires Ruby version >= 2.2.2.
```